# Generated by Django 5.1.14 on 2026-02-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='estimated_delivery_time',
            field=models.IntegerField(default=30),
        ),
    ]
