# Generated by Django 5.1.14 on 2026-02-23 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_initial'),
        ('restaurants', '0003_alter_restaurant_estimated_delivery_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('table', 'reservation_date', 'reservation_time'), name='unique_table_booking_time'),
        ),
    ]
