export const ORDER_TYPES = {
  DELIVERY: 'DELIVERY',
  PICKUP: 'PICKUP',
};

export const ORDER_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  READY: 'READY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const PAYMENT_METHODS = {
  CARD: 'CARD',
  CASH: 'CASH',
};

export const PAYMENT_STATUSES = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const NOTIFICATION_TYPES = {
  ORDER: 'ORDER',
  RESERVATION: 'RESERVATION',
  PROMOTION: 'PROMOTION',
  SYSTEM: 'SYSTEM',
};

export const TICKET_CATEGORIES = {
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  RESERVATION: 'RESERVATION',
  ACCOUNT: 'ACCOUNT',
  TECHNICAL: 'TECHNICAL',
  FEEDBACK: 'FEEDBACK',
  OTHER: 'OTHER',
};

export const TICKET_STATUSES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

export const RESERVATION_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
};

export const USER_ROLES = {
  CUSTOMER: 'CUSTOMER',
  RESTAURANT_OWNER: 'RESTAURANT_OWNER',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
};

export const STATUS_COLORS = {
  PENDING: 'warning',
  CONFIRMED: 'primary',
  PREPARING: 'primary',
  READY: 'success',
  OUT_FOR_DELIVERY: 'primary',
  DELIVERED: 'success',
  CANCELLED: 'error',
  COMPLETED: 'success',
  FAILED: 'error',
  OPEN: 'primary',
  IN_PROGRESS: 'warning',
  RESOLVED: 'success',
  CLOSED: 'gray',
};
